{
 "title": "Woodpecker",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "cluster", "label": "cluster", "query": "label_values(cluster)" },
   { "name": "model", "label": "model", "query": "label_values(model)" }
  ]
 },
 "panels": [
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(system_n_cpus)" }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(mem_total)" }
   ]
  },
  {
   "title": "Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(disk_total)" }
   ]
  },
  {
   "title": "Disks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(disk_total)" }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU %",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(cpu_usage_user{cpu=\"cpu-total\"})",
       "legendFormat": "user"
      },
      {
       "expr": "sum(cpu_usage_iowait{cpu=\"cpu-total\"})",
       "legendFormat": "iowait "
      },
      {
       "expr": "sum(cpu_usage_nice{cpu=\"cpu-total\"})",
       "legendFormat": "nice"
      },
      {
       "expr": "sum(cpu_usage_softirq{cpu=\"cpu-total\"})",
       "legendFormat": "softirq "
      },
      {
       "expr": "sum(cpu_usage_irq{cpu=\"cpu-total\"})",
       "legendFormat": "irq"
      },
      {
       "expr": "sum(cpu_usage_system{cpu=\"cpu-total\"})",
       "legendFormat": "system "
      },
      {
       "expr": "sum(cpu_usage_idle{cpu=\"cpu-total\"})",
       "legendFormat": "idle"
      }
     ]
    },
    {
     "title": "Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(diskio_reads{name!~\".*(bcache|loop|crypt|n1p|ceph).*\"}[5m]))",
       "legendFormat": "read"
      },
      {
       "expr": "sum(irate(diskio_writes{name!~\".*(bcache|loop|crypt|n1p|ceph).*\"}[5m]))",
       "legendFormat": "write"
      },
      {
       "expr": "sum(irate(diskio_reads{name=~\".*bcache.*\"}[5m]))",
       "legendFormat": "read - bcache"
      },
      {
       "expr": "sum(irate(diskio_writes{name=~\".*bcache.*\"}[5m]))",
       "legendFormat": "write - bcache"
      }
     ]
    },
    {
     "title": "Network throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      { "expr": "sum(irate(net_bytes_recv[5m]))", "legendFormat": "received" },
      { "expr": "sum(irate(net_bytes_sent[5m]))", "legendFormat": "sent" }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(system_load1[5m]))  ",
       "legendFormat": "1 min"
      },
      {
       "expr": "sum(avg_over_time(system_load5[5m]))",
       "legendFormat": "5 min"
      },
      {
       "expr": "sum(avg_over_time(system_load15[5m]))  ",
       "legendFormat": "15 min"
      }
     ]
    },
    {
     "title": "Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(diskio_read_bytes{name!~\".*(bcache|loop|crypt|n1p).*\"}[5m]))",
       "legendFormat": "read"
      },
      {
       "expr": "sum(irate(diskio_write_bytes{name!~\".*(bcache|loop|crypt|n1p).*\"}[5m]))",
       "legendFormat": "write"
      },
      {
       "expr": "sum(irate(diskio_read_bytes{name=~\".*bcache.*\"}[5m]))",
       "legendFormat": "read - bcache"
      },
      {
       "expr": "sum(irate(diskio_write_bytes{name=~\".*bcache.*\"}[5m]))",
       "legendFormat": "write - bcache"
      }
     ]
    },
    {
     "title": "Bcache Dirty Data",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "sum(bcache_dirty_data)", "legendFormat": "Dirty Data" }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "sum(mem_used)", "legendFormat": "Used" },
      { "expr": "sum(mem_free)  ", "legendFormat": "Free" },
      { "expr": "sum(mem_buffered + mem_cached)", "legendFormat": "Buffers/Cache" }
     ]
    },
    {
     "title": "Bcache Cache Hit Ratio",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "expr": "avg(bcache_cache_hit_ratio)", "legendFormat": "Hit ratio (avg)" }
     ]
    }
   ]
  },
  {
   "title": "Ceph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(ceph_osd_op_w_in_bytes[$interval]))",
       "legendFormat": "Write"
      },
      {
       "expr": "sum(irate(ceph_osd_op_r_out_bytes[$interval]))",
       "legendFormat": "Read"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(ceph_osd_op_w[$interval]))",
       "legendFormat": "Write"
      },
      {
       "expr": "sum(irate(ceph_osd_op_r[$interval]))",
       "legendFormat": "Read"
      }
     ]
    },
    {
     "title": "Avg OSD  Op  Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "expr": "avg(ceph_osd_apply_latency_ms)", "legendFormat": "apply (average)" },
      {
       "expr": "quantile(0.95, ceph_osd_apply_latency_ms)",
       "legendFormat": "apply (95 percentile)"
      }
     ]
    }
   ]
  },
  { "title": "Client FIO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Mean Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(fio_read_bandwidth) / 1024", "legendFormat": "Read" },
    {
     "expr": "sum(fio_write_bandwidth) / 1024",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Max Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "sum(fio_read_bandwidth) / 1024", "legendFormat": "Read" },
    {
     "expr": "sum(fio_write_bandwidth) / 1024",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Mean Client Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(fio_read_bandwidth)", "legendFormat": "Read" },
    { "expr": "avg(fio_write_bandwidth)", "legendFormat": "Write" }
   ]
  },
  {
   "title": "Mean Total IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(fio_read_iops)", "legendFormat": "Read" },
    { "expr": "sum(fio_write_iops)", "legendFormat": "Write" }
   ]
  },
  {
   "title": "Max Total IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "sum(fio_read_iops)", "legendFormat": "Read" },
    { "expr": "sum(fio_write_iops)", "legendFormat": "Write" }
   ]
  },
  {
   "title": "Mean Client IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(fio_read_iops)", "legendFormat": "Read" },
    { "expr": "avg(fio_write_iops)", "legendFormat": "Write" }
   ]
  },
  {
   "title": "Max Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "jobs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "count(fio_read_latency)", "legendFormat": "Readers" },
    { "expr": "count(fio_write_latency)", "legendFormat": "Writers" }
   ]
  },
  {
   "title": "Mean Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(fio_read_latency)", "legendFormat": "Read" },
    { "expr": "avg(fio_write_latency)", "legendFormat": "Write" }
   ]
  },
  {
   "title": "90%tile Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(fio_read_clat_90_000000)", "legendFormat": "Read" },
    { "expr": "avg(fio_write_clat_90_000000)", "legendFormat": "Write" }
   ]
  },
  {
   "title": "99%tile Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(fio_read_clat_99_000000)", "legendFormat": "Read" },
    { "expr": "avg(fio_write_clat_99_000000)", "legendFormat": "Write" }
   ]
  },
  {
   "title": "99.9%tile Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(fio_read_clat_99_900000)", "legendFormat": "Read" },
    { "expr": "avg(fio_write_clat_99_900000)", "legendFormat": "Write" }
   ]
  },
  {
   "title": "FIO Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    { "expr": "sum(fio_read_bandwidth)", "legendFormat": "read" },
    { "expr": "sum(fio_write_bandwidth)", "legendFormat": "write" }
   ]
  },
  {
   "title": "FIO IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    { "expr": "sum(fio_read_iops)", "legendFormat": "read" },
    { "expr": "sum(fio_write_iops)", "legendFormat": "write" }
   ]
  },
  {
   "title": "FIO latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "avg(fio_read_clat_mean)", "legendFormat": "read" },
    { "expr": "avg(fio_write_clat_mean)", "legendFormat": "write" },
    { "expr": "avg(fio_read_clat_90_000000)", "legendFormat": "read - 90%tile" },
    { "expr": "avg(fio_write_clat_90_000000)", "legendFormat": "write - 90%tile" }
   ]
  },
  {
   "title": "FIO Bandwidth (per client)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(fio_read_bandwidth[5m])",
     "legendFormat": "{{unit}} - read"
    },
    {
     "expr": "avg_over_time(fio_write_bandwidth[5m])",
     "legendFormat": "{{unit}} - write"
    }
   ]
  },
  {
   "title": "FIO IOPS (per client)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(fio_read_iops[5m])",
     "legendFormat": "{{unit}} - read"
    },
    {
     "expr": "avg_over_time(fio_write_iops[5m])",
     "legendFormat": "{{unit}} - write"
    }
   ]
  },
  {
   "title": "FIO clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(fio_read_bandwidth{juju_unit=~\".*\"}) by (juju_unit))\n",
     "legendFormat": "readers"
    },
    {
     "expr": "count(count(fio_write_bandwidth{juju_unit=~\".*\"}) by (juju_unit))\n",
     "legendFormat": "writers"
    }
   ]
  }
 ]
}